# Generated by Django 3.1.3 on 2021-04-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('podcast_name', models.CharField(max_length=100)),
                ('duration_in_sec', models.DurationField()),
                ('upload_time', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('duration_in_sec', models.DurationField()),
                ('upload_time', models.DateTimeField()),
            ],
        ),
    ]
