# Generated by Django 3.1.3 on 2021-04-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server_webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='audiobook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audiobook_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_sec', models.DurationField()),
                ('upload_time', models.DateTimeField()),
            ],
        ),
    ]
