# Generated by Django 3.1.3 on 2021-04-07 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server_webApp', '0004_auto_20210407_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 9, 39, 41, 335859)),
        ),
    ]
